# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(help_text='unique handle of the AbsIngredient', max_length=128, unique=True)),
                ('display_name', models.CharField(max_length=128)),
                ('description', models.TextField(help_text='Human-friendly description')),
                ('co2_kg', models.DecimalField(decimal_places=2, help_text='CO2 footprint per 1kg', max_digits=5)),
                ('energy_kg', models.DecimalField(decimal_places=2, help_text='kWh footprint per 1kg', max_digits=5)),
                ('water_kg', models.DecimalField(decimal_places=2, help_text='liters of water per ingredient', max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='APIUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.DecimalField(decimal_places=3, help_text='Quantity of the item (kg)', max_digits=5)),
                ('display_name', models.CharField(help_text='Saved display name of ingredient', max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Saved display name of ingredient', max_length=128)),
                ('concentration', models.DecimalField(decimal_places=2, help_text='Percentage', max_digits=4)),
                ('co2_fp', models.DecimalField(decimal_places=2, help_text='Computed co2 footprint (kg)', max_digits=7)),
                ('energy_fp', models.DecimalField(decimal_places=2, help_text='Computed energy footprint (kWh)', max_digits=7)),
                ('water_fp', models.DecimalField(decimal_places=2, help_text='Computed water footprint (l)', max_digits=7)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.APIUser')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Receipt'),
        ),
    ]
