# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absingredient',
            options={'ordering': ['handle'], 'verbose_name': 'abstract ingredient'},
        ),
        migrations.AlterModelOptions(
            name='apiuser',
            options={'ordering': ['email']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created'], 'verbose_name': 'receipt item'},
        ),
        migrations.AlterModelOptions(
            name='itemingredient',
            options={'ordering': ['display_name'], 'verbose_name': 'item ingredient'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='itemingredient',
            name='abs_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datastore.AbsIngredient'),
        ),
    ]
