# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0002_auto_20180915_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemingredient',
            name='co2_fp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Computed co2 footprint (kg)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='itemingredient',
            name='concentration',
            field=models.DecimalField(decimal_places=2, help_text='Percentage (0-1)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='itemingredient',
            name='energy_fp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Computed energy footprint (kWh)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='itemingredient',
            name='water_fp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Computed water footprint (l)', max_digits=7),
        ),
    ]
