# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0003_auto_20180915_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Price of the item (denominated in the currency of the receipt)', max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='currency',
            field=models.CharField(default='EUR', max_length=4),
        ),
        migrations.AddField(
            model_name='receipt',
            name='shop',
            field=models.CharField(blank=True, help_text='Shop name', max_length=128),
        ),
        migrations.AlterField(
            model_name='absingredient',
            name='co2_kg',
            field=models.DecimalField(decimal_places=2, help_text='Kg CO2 footprint per 1kg', max_digits=5),
        ),
        migrations.AlterField(
            model_name='absingredient',
            name='energy_kg',
            field=models.DecimalField(decimal_places=2, help_text='MegaJoules footprint per 1kg', max_digits=5),
        ),
        migrations.AlterField(
            model_name='absingredient',
            name='handle',
            field=models.CharField(blank=True, help_text='unique handle of the AbsIngredient', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='absingredient',
            name='water_kg',
            field=models.DecimalField(decimal_places=2, help_text='cubic meters of water per 1kg', max_digits=5),
        ),
        migrations.AlterField(
            model_name='itemingredient',
            name='energy_fp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Computed energy footprint (MJ)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='itemingredient',
            name='water_fp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Computed water footprint (m^3)', max_digits=7),
        ),
    ]
